### ISSUE TITLE
IP copying is no longer working

### ISSUE THREAD

**Issue by LeanoJ** [WemXPro/tracker#289]
### Product

WemX

### Describe the issue

Copying the IP in the dashboard area no longer works 

![image](https://github.com/WemXPro/tracker/assets/123408114/2a6ea890-fc3c-499a-81fe-a1812a45e169)

### Product Version

dev

### Pterodactyl Panel Version

1.11.5

**Comment by VanillaChan6571** [comment]
Fixed in dev OR never was an issue?

**Comment by Pvpsmash** [comment]
It was working prior to dev, If i recall correctly.
Now, it just promts "Copy" and outputs string "Copy" back to paste, the IP's were working before web I know for a fact. Unsure which dev version broke it. I'm still getting the same issue.

**Comment by VanillaChan6571** [comment]
> It was working prior to dev, If i recall correctly. Now, it just promts "Copy" and outputs string "Copy" back to paste, the IP's were working before web I know for a fact. Unsure which dev version broke it. I'm still getting the same issue.

I do know if it says "Copy" and you clicked on it again it will copy the "Copy" text instead of the ip. So...dont click on the button twice... (This is still a bug and an easy fix for a patch update)

**Comment by Pvpsmash** [comment]
> > It was working prior to dev, If i recall correctly. Now, it just promts "Copy" and outputs string "Copy" back to paste, the IP's were working before web I know for a fact. Unsure which dev version broke it. I'm still getting the same issue.
> 
> I do know if it says "Copy" and you clicked on it again it will copy the "Copy" text instead of the ip. So...dont click on the button twice... (This is still a bug and an easy fix for a patch update)

My dashboard does not show any IP Addressess since dev version though...?

Assumed that was part of the bug also.
Maybe I'm an isolated case, although I'm running latest wemx (and modules) ontop so unsure of the problem im having currently.

**Comment by VanillaChan6571** [comment]
> > > It was working prior to dev, If i recall correctly. Now, it just promts "Copy" and outputs string "Copy" back to paste, the IP's were working before web I know for a fact. Unsure which dev version broke it. I'm still getting the same issue.
> > 
> > 
> > I do know if it says "Copy" and you clicked on it again it will copy the "Copy" text instead of the ip. So...dont click on the button twice... (This is still a bug and an easy fix for a patch update)
> 
> My dashboard does not show any IP Addressess since dev version though...?
> 
> Assumed that was part of the bug also. Maybe I'm an isolated case, although I'm running latest wemx (and modules) ontop so unsure of the problem im having currently.

If there is no ip and you are using tailwind “default client theme” the server was never created.

**Comment by GIGABAIT93** [comment]
Привіт у вас все ще виникає проблема з копіюванням іп?

**Comment by LeanoJ** [comment]
@GIGABAIT93 No, not anymore. I forgot to tell you that it's working again.
